name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xstars
    steps:
      - uses: actions/checkout@v4
        with:
          path: xstars
      - uses: actions/checkout@v4
        with:
          repository: xstarust/xcal
          path: xcal
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo test --workspace --all-targets
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo package -p xstars --allow-dirty --config 'patch.crates-io.xcal.path="../xcal"'
